#!/usr/bin/env php
<?php

if (php_sapi_name() != 'cli') {
    die('This command can only be used in CLI mode.');
}

if (isset($argv[1])) {
    if (in_array($argv[1], ['-h', '--help'])) {
        $command_help = "generate_sources - Create .txt sources files (supported locales and repositories)\n" .
                "Usage: generate_sources [config_folder]\n\n" .
                "Example: generate_sources app/config\n";
        die($command_help);
    }
}

if (count($argv) < 3) {
    die("This command needs more parameters, please check generate_sources --help.\n");
}

$config_folder = realpath($argv[1]);
$uri = $argv[2];

if (! $repositories = json_decode(file_get_contents($uri), true)) {
    error_log('JSON source is not valid or not reachable.');
    exit(1);
}

foreach ($repositories as $repository) {
    if ($repository['enabled']) {
        // Save supported locales for each repository
        echo "* Saving list of locales for {$repository["id"]}\n";
        $file_name = "{$config_folder}/sources/{$repository["id"]}.txt";
        file_put_contents($file_name, implode("\n", $repository['locales']) . "\n");
    }
}

// Create a JSON file with the list of all supported repositories in the correct order
$json_repositories = [];
foreach ($repositories as $repository) {
    if ($repository['enabled']) {
        $json_repositories[intval($repository['display_order'])] = [
            'id'   => $repository['id'],
            'name' => $repository['name']
        ];
    }
}
ksort($json_repositories);
echo "* Saving JSON record of all supported repositories\n";
$file_name = "{$config_folder}/sources/supported_repositories.json";
file_put_contents($file_name, json_encode($json_repositories));

// Create list of locales working in tools like Pootle and Pontoon
$uri = "{$uri}/?tool=all";
if (! $file_content = file_get_contents($uri)) {
    error_log('JSON source is not reachable.');
    exit(1);
}
echo "* Saving JSON record of tools and their supported locales\n";
$file_name = "{$config_folder}/sources/tools.json";
file_put_contents($file_name, $file_content);
